### ISSUE TITLE
Faulty CartGiftCardItemSnake Type

### ISSUE THREAD

**Issue by BelphegorPrime** [swellstores/swell-js#101]
Here is some misstake:
https://github.com/swellstores/swell-js/blob/master/types/cart/snake.d.ts#L34

Why is such a version with such errors even published?

**Comment by ericingram** [comment]
Good question! Thanks for pointing it out

**Comment by igor-augustynski-furba** [comment]
Still an issue in the latest version (3.22.0). The pull request has been merged but no new versions have been published. It's a very important issue as my pipelines keep breaking over this.

**Comment by BelphegorPrime** [comment]
I reopened the PR
