### ISSUE TITLE
Error using the library

### ISSUE THREAD

**Issue by kevinccbsg** [swellstores/swell-js#13]
In our team, we have an enterprise Swell account and we tried to install this package and use it but after following the first step we are getting a CORS error.

<img width="1435" alt="Screen Shot 2020-03-04 at 00 25 34" src="https://user-images.githubusercontent.com/12685053/75858260-1d1e0280-5df8-11ea-966d-93be032fca4b.png">

This is the code we want to test:

<img width="737" alt="Screen Shot 2020-03-04 at 00 26 04" src="https://user-images.githubusercontent.com/12685053/75858424-77b75e80-5df8-11ea-98e0-d8e44cfc8171.png">

We also try with a plugin to disable CORS and we get the next error:

<img width="815" alt="Screen Shot 2020-03-04 at 00 27 49" src="https://user-images.githubusercontent.com/12685053/75858328-42ab0c00-5df8-11ea-9453-c8c03818449d.png">

That error does not make sense as we have that configured.

**Comment by ericingram** [comment]
@vstudenichnik-insoft can you look into this?

**Comment by kevinccbsg** [comment]
is there any update on this? 🤔

**Comment by kevinccbsg** [comment]
How can we use the library? Or docs are wrong or this cannot be used by anyone. 😓 Maybe we need to set up something else in our store to skip the CORS error? 🤔

**Comment by papertokyo** [comment]
Hey @kevinccbsg, could you check that:
- You're using the latest version of Swell.js (3.2.2)
- Whether you are able to make other requests with the library? (e.g. `swell.products.list()`)

The `createElements` method relies on Stripe.js, so there might be an issue there if you're still seeing an error. 
Our [reference storefront implementation](https://github.com/swellstores/origin-theme) is powered by Swell.js, though it doesn't implement checkout/payments right now.

**Comment by kevinccbsg** [comment]
Hi @papertokyo, thanks for your response. We are still getting the same error.

These screenshots are provided using the `reference storefront implementation`.

<img width="1416" alt="Screen Shot 2020-10-22 at 11 58 12" src="https://user-images.githubusercontent.com/12685053/96856204-f16e8c00-145d-11eb-9a3a-af854fdb5d50.png">
<img width="1423" alt="Screen Shot 2020-10-22 at 11 58 19" src="https://user-images.githubusercontent.com/12685053/96856271-03e8c580-145e-11eb-9e60-9e4f1df75eb1.png">

**Comment by ericingram** [comment]
@kevinccbsg sorry for the delay on this, looks like it got lost in the shuffle

The CORS error actually occurs because of an authentication error, so it's likely an invalid store ID/public key combination

Side note: we just pushed an update to this library (3.3.0) that implements stripe elements for Klarna/iDEAL (updates to the readme are coming soon)

Pass your test code including public key to our support team and they'll check the credentials right away

**Comment by kevinccbsg** [comment]
Thanks @ericingram

**Comment by kevinccbsg** [comment]
It is working now @ericingram @papertokyo so I think this can be closed

**Comment by adrrian17** [comment]
Hi, I have the same issue, **Error: Store is not active or not configured for API access** and I'm using the latest version of Swell.js (3.19.3)
