### ISSUE TITLE
Unable to see access the Swell admin/test dashboard

### ISSUE THREAD

**Issue by Daniel-Alamezie** [swellstores/swell-js#134]
![image](https://github.com/swellstores/swell-js/assets/74880857/0948c350-700b-43d2-b1cd-9933acc77bb2)
Swell dashboard is currently down and returns an error 404.

**Comment by Daniel-Alamezie** [comment]
I can switch between live and test on the dashboard either

**Comment by steven-k1** [comment]
@Daniel-Alamezie Taking a look

**Comment by Daniel-Alamezie** [comment]
Thank you

**Comment by steven-k1** [comment]
@Daniel-Alamezie Looks like the issue was only affecting the test environment. A fix has been applied, though, and the issue should be resolved now. You might need to log out and back in to see the fix.

**Comment by Daniel-Alamezie** [comment]
@steven-k1  it has, I appreciate the swift. response thank you very much.
