### ISSUE TITLE
Unable to change the Photo of the Account of Swell dashboard

### ISSUE THREAD

**Issue by Daniel-Alamezie** [swellstores/swell-js#135]
I am currently unable to change the profile pic on the my swell account on the admin dashboard.
![image](https://github.com/swellstores/swell-js/assets/74880857/9a816896-eaca-41c3-8717-4af3f05e3a16)

**Comment by Daniel-Alamezie** [comment]
There is also a slight UI typo, that could be potentially fixed on the setting/account/admin
![image](https://github.com/swellstores/swell-js/assets/74880857/7be1840c-dd82-4c78-ad11-9898de433bc1)

**Comment by Daniel-Alamezie** [comment]
Also it says i have made 50.8K api calls, i dont know how swell calculates it api call. I am the only one making calls to the is store atm as it is still under development, and i dont think i have made 50k api calls, will someone be able to explain how the api calls are calculated.

**Comment by ericingram** [comment]
Thanks for the feedback @Daniel-Alamezie, we’ll get that fixed.

Can you share your store ID with our support team and they will look into the API calls. They are recorded with each request to the API.

**Comment by Daniel-Alamezie** [comment]
Thank you for reaching out. I will reach out to them on that. but I still cant change the picture on my swell dashboard

**Comment by swellmike** [comment]
this is fixed
