### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by krupchic** [swellstores/swell-js#17]
Could you please move lodash to dependencies to avoid this err:
![image](https://user-images.githubusercontent.com/17881992/76614666-996bc080-6531-11ea-99a8-67a5cda450bd.png)

![image](https://user-images.githubusercontent.com/17881992/76614626-82c56980-6531-11ea-9804-d4b95a808b4d.png)

**Comment by vstudenichnik-insoft** [comment]
@krupchic @ericingram [PR](https://github.com/swellstores/swell-js/pull/16)
