### ISSUE TITLE
Swell v4.0.7+: Cart & Product Typescript inconsistencies

### ISSUE THREAD

**Issue by fourwordsnz** [swellstores/swell-js#175]
I updated to Swell's latest version (4.0.9) but ran into TypeScript inconsistencies with docs and response. 

**Issue 1 – Attributes Values Key for Products & Product Variants**

- Attributes Type Interface has the key set as `values`
- But the API response returns this as `value`

I'm having response generated  via `swell.products.variation()` or via `swell.products.get(slug)`

Example: 
<img width="565" alt="Screenshot 2024-04-24 at 7 31 59 PM" src="https://github.com/swellstores/swell-js/assets/77376937/d6ae643e-656f-4374-a640-2a52f832e361">

**Issue 2 – addItem: CartItem**

Using `swell.cart.addItem(product)` and sending an object with keys below:

`{
  product_id,
  quantity,
  variant_id,
  metadata
}`

With the update, now getting a type error, not assignable to `CartItem`. It now expects `id` to be included. 

[Per docs](https://developers.swell.is/frontend-api/carts#add-an-item), the object is what should be sent. Functionality wise there are no issues. Just a type issue. I can ignore it. 

But is this expected or something on my end?

**Comment by awwit** [comment]
@fourwordsnz good catch! We have released `v4.1.0` with a fix.
