### ISSUE TITLE
Client request appears to fail to include public key

### ISSUE THREAD

**Issue by sebpowell** [swellstores/swell-js#194]
Hello, 

I've just tried connecting to my storefront using this library and by following the instructions provided here: https://developers.swell.is/frontend-api/setup. 

Here's a sample of my code (Next.js 14, app directory):

```TS
import swell from "swell-js";

export default async function Home() {
  try {
    swell.init("<store_id>", "<public_key>";

    const t = await swell.products.list({
      limit: 25,
      page: 1,
    });
  } catch (e) {
    console.log(e);
  }

  return <HomePage />;
}
```

This returns the following:

```JSON
{
    "error": {
        "code": "AUTHENTICATION",
        "message": "You must authenticate with your public key. Also, make sure withCredentials is enabled for all requests."
    }
}
```

I checked the network request, and it doesn't look like the public_key is being included in the request:

<img width="1298" alt="Screenshot 2024-10-17 at 10 30 43" src="https://github.com/user-attachments/assets/3cbb52a4-2620-41b5-9624-35e937985406">

There is an authorisation header included that contains the following value:

```
Basic cGtfdGVzdF82UTRtUldUTHJyRG1iMExFaEJBVmF2WU9zaTFVRXBpTg==
```

I'm not sure what this token is (it isn't my public_key). Not sure if this is a bug, or if I'm doing something wrong?

**Comment by ericingram** [comment]
The `Basic ...` is referring to the public key base64 encoded. Otherwise it certainly should work, so I would double check the store ID and key

**Comment by sebpowell** [comment]
@ericingram – really weird, it's working now. 

I noticed the store ID changed on the API access page – when I tried it this morning it was a random string that looked something like this: lr1231ab – now it's my actual store name. I may have been looking at an old tab or something, not sure what happened. 

Anyway, it's working now – thanks for your help, closing this.
