### ISSUE TITLE
Typescript Issue in 4.2.4 No Default Export

### ISSUE THREAD

**Issue by jeff-wood-readyup** [swellstores/swell-js#195]
I am having an issue with Typescript, it is saying the swell-js library does not have a default export and so it is not able to pull in the type definitions correctly, resulting in it defaulting to an any type.

<img width="1293" alt="Screenshot 2024-11-14 at 11 35 59 PM" src="https://github.com/user-attachments/assets/61f42e85-02a3-4736-b0d9-90159f7194a1">
<img width="1140" alt="Screenshot 2024-11-14 at 11 36 10 PM" src="https://github.com/user-attachments/assets/5f9d53fd-4613-4c30-945a-66ccd72ef491">
<img width="1023" alt="Screenshot 2024-11-14 at 11 36 19 PM" src="https://github.com/user-attachments/assets/22c0767d-67f6-416d-b02b-c3c966ba78eb">

My package.json dependencies:

```  
"dependencies": {
    "@quasar/extras": "^1.16.4",
    "axios": "^1.2.1",
    "pinia": "^2.0.11",
    "quasar": "^2.16.0",
    "swell-js": "^4.2.2",
    "vue": "^3.4.18",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@quasar/app-vite": "^2.0.0-beta.12",
    "@types/node": "^22.9.0",
    "@typescript-eslint/eslint-plugin": "^8.14.0",
    "@typescript-eslint/parser": "^8.14.0",
    "autoprefixer": "^10.4.2",
    "dotenv": "^16.4.5",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-vue": "^9.0.0",
    "prettier": "^3.0.3",
    "prettier-eslint": "^16.3.0",
    "typescript": "~5.5.3",
    "vite-plugin-checker": "^0.8.0",
    "vue-tsc": "^2.0.29"
  },
```

Any help resolving this would be greatly appreciated, my code itself works fine but the type errors are very annoying to deal with. Thanks!

**Comment by awwit** [comment]
@jeff-wood-readyup what if you try to import it this way:

```ts
import * as swell from 'swell-js';
```

**Comment by ericingram** [comment]
@awwit we should fix if true

**Comment by jeff-wood-readyup** [comment]
> @jeff-wood-readyup what if you try to import it this way:
> 
> ```ts
> import * as swell from 'swell-js';
> ```

This was actually one of the first things I tried and it does remove the typescript error but it stops my code from actually working. 

<img width="653" alt="Screenshot 2024-11-15 at 10 11 35 AM" src="https://github.com/user-attachments/assets/da44ce05-7cf0-4108-b2d9-b68d51103e48">
![Screenshot 2024-11-15 at 10 11 23 AM](https://github.com/user-attachments/assets/c9fa01b6-02ef-4829-94b0-914e2e65d2ae)

It seems that this method is importing the namespace for the types instead of actually importing the library at all.

**Comment by jeff-wood-readyup** [comment]
Doing a little poking around myself I added this to the end of the index.d.ts file and it seems to have solved my problem.

```
declare const swell: {
  version: string;
  init: typeof init;
  account: typeof account;
  attributes: typeof attributes;
  card: typeof card;
  cart: typeof cart;
  categories: typeof categories;
  content: typeof content;
  currency: typeof currency;
  locale: typeof locale;
  payment: typeof payment;
  products: typeof products;
  settings: typeof settings;
  subscriptions: typeof subscriptions;
  invoices: typeof invoices;
  session: typeof session;
  functions: typeof functions;
  utils: typeof utils;
  auth: typeof init;
  request: typeof request;
  get: typeof get;
  put: typeof put;
  post: typeof post;
  delete: typeof _delete;
};

export default swell;
```

**Comment by jeff-wood-readyup** [comment]
PR with fix is here - https://github.com/swellstores/swell-js/pull/197

**Comment by jeff-wood-readyup** [comment]
@swellmike @ericingram just wanted to check in ton this issue to see if there are any updates? Thanks.

**Comment by ericingram** [comment]
Thanks @jeff-wood-readyup!
