### ISSUE TITLE
Problems updating the paiment status at Swell

### ISSUE THREAD

**Issue by adrian-afergon** [swellstores/swell-js#25]
Hello, we are having some troubles updating the cart/order based on billing property at the end of the process.

We have followed the [iDeal integration](https://github.com/swellstores/swell-js/blob/master/stripe_klarna_ideal.md#ideal-integration). We have completed the process, but when we goes to `swell` the status are iDeal - Unpaid:
![image](https://user-images.githubusercontent.com/6615775/96606968-c534fd00-12ef-11eb-96f2-4a5009d302ed.png)

When we access to the order, we can charge the order:
![image](https://user-images.githubusercontent.com/6615775/96607081-e39af880-12ef-11eb-96c6-e67db2a3d5a6.png)

However this process should be made manually, so we would like to make it on a more automatically way. We suppose that it happens because at `billing `object we use the property `requires_confirmation`, but we don't know wich other status can we use at this field to change the order status to `paid`.

Our payment intent creation is the following:
```
const paymentIntent = await stripe.paymentIntents.create({
  payment_method: paymentMethod ? paymentMethod.id : undefined,
  amount: order.sub_total * 100, //it should receive integers
  receipt_email: user.email,
  currency: 'eur', // ideal method only accept eur currency
  payment_method_types: ['ideal'],
});
```

Instead using `handleCartAction` method we are usign `confirmIdealPayment` like this (we can't set the url at backend because we handle multiple front-end applications with diferent urls, but I think that It's not the issue):
```
const cardAction = await paymentService?.confirmIdealPayment(paymentSecret, {
  return_url: `${window.location.origin}/purchase-status/${cartId}`
})
```

And our current billing object looks like this:
```
const billing = {
  method: 'ideal',
    ideal: {
      token: paymentIntent.payment_method,
    },
    stripe_payment_intent: {
      id: paymentIntent.id,
        status: 'requires_confirmation',
    },
};
```

Can you help us? Maybe we are doing things on the wrong way, or we miss something about the process.

Thank you!

**Comment by ericingram** [comment]
@adrian-afergon your example should work I believe, because when Swell received the `status: requires_confirmation` it will call `paymentIntent.confirm` on it to essentially auto capture the payment.

Can you pass your account/order ID to someone on our support team and we'll make sure to dig into it more?

Thank you!

**Comment by ericingram** [comment]
@adrian-afergon actually, looks like we found a problem with the `status` value, we're working on it

**Comment by adrian-afergon** [comment]
@ericingram sure, the account is `noordhoff-dev` and the order id is `5f8952c6acb3431a72f3633e`

Thank you a lot for your help, we will be waiting for it! 😄 

CC: @cliftonc @imartea

**Comment by ericingram** [comment]
@adrian-afergon we found another way to handle `status` and it's now not necessary as part of this flow (doc updated)

Everything else in your example looks correct, but please try it again with this final billing object result:

```
const billing = {
  method: 'ideal',
  ideal: {
    token: paymentIntent.payment_method,
  },
  stripe_payment_intent: {
    id: paymentIntent.id,
  },
};
```

**Comment by adrian-afergon** [comment]
@ericingram Thank you for your help!

I just test your suggestion, however the result is the same, for request:
```
// PUT: https://noordhoff-dev:*********@api.swell.store/orders/5f905cc08248540804576d1f
{
  "billing": {
    "method": "ideal",
    "ideal": {
      "token": "pm_********"
    },
    "stripe_payment_intent": {
      "id": "pi_********"
    }
  }
}
```

Is the same, the order status is unpaid

![image](https://user-images.githubusercontent.com/6615775/96749772-2679d080-13c3-11eb-945a-c6a73620cf08.png)

This time to be faster and give you feedback, I tried directly on Postman, but is the same process.

**Comment by ericingram** [comment]
@adrian-afergon I'm going to email you directly so it's a little faster to debug :)
