### ISSUE TITLE
`cart.addItem` mutates input options objects

### ISSUE THREAD

**Issue by m59peacemaker** [swellstores/swell-js#34]
The key `name` is replaced with `id`. I would be on the lookout for other such mutations. This is a source of devastating and very difficult to track down bugs.

Example:
```js
const item = { product_id, quantity: 1, options: [ { name: 'Size', value: '1 cup' } ] }
swell.cart.addItem(item)
item.options[0] // => { id: 'Size', value: '1 cup' }
```

I use the `item` object for more than just the call to `addItem`, and having it mutated is a big issue. I have to pass swell a copy to avoid this.

**Comment by m59peacemaker** [comment]
This function is the source of the issue: https://github.com/swellstores/swell-js/blob/842da1eb4c8d38765f45e42793f903fed4f7890e/src/products.js#L55

**Comment by ericingram** [comment]
@m59peacemaker good catch! I just pushed a patch fix for this issue
