### ISSUE TITLE
Custom filed type boolean with wrong response

### ISSUE THREAD

**Issue by Florian-crg** [swellstores/swell-js#47]
I created a custom filed to my Products named **is_new**
Using the swell console the field is false, like set in the swell dashboard. But using swell.js the value is true. 

Response exemple from the consoles

From https://<-name->.swell.store/admin/console?get/products 

```
"is_new": false,
"id": "60f6885f9fd1616cab3d1aad",
```

And from my basic react app 
```
id: "60f6885f9fd1616cab3d1aad"
is_new: true
```

**Comment by rodrigoddalmeida** [comment]
@Florian-crg this is the intended behavior of our caching mechanism, you should be able to clear it manually or disable caching in development:

```js
swell.cache.clear() // programmatically clears cache
swell.cache.enabled = false // disables caching globally
swell.cache.enabled = true // re-enables caching
```
