### ISSUE TITLE
swell.payment.createElements is throwing error: cartApi.methods is not a function

### ISSUE THREAD

**Issue by Flaxxas** [swellstores/swell-js#48]
Hey! :) As written in the title, I get an error when calling `swell.payment.createElements`.

Error: `TypeError: da.methods is not a function` (da = cartApi)
It get's thrown [here](https://github.com/swellstores/swell-js/blob/master/src/payment.js#L37). 

My (very short) code-snippet: 
```js
swell.payment.createElements({
  card: {
    elementId: 'card-element-id'
  }
})
```

Is anyone else experiencing this or am I the only one and should investigate this issue further?

**Comment by greph** [comment]
Hi @Flaxxas , are you still seeing the error after pulling in latest, and initializing Swell with:
` swell.init('my-store', 'pk_xxx')`?

**Comment by Flaxxas** [comment]
Hey @greph! We were using the version 4.0.0-next.0 - this was used in the Next.js commerce kit. Should've mentioned that, sorry. When using version 3.10.0, there's no error thrown, <s>but also no element rendered</s> and it works when a stripe account is connected. Thanks for leading me in the right direction!

**Comment by greph** [comment]
Great to hear, thanks for the update @Flaxxas !

**Comment by achadee** [comment]
@Flaxxas @greph 

Having this exact issue:

```
da.methods is not a function
```

not sure how to fix, as ive changed version numbers and initialized 

thanks

**Comment by achadee** [comment]
Sorry after deleting my node modules it worked
