### ISSUE TITLE
Custom_Fields not showing up Product.Variants 

### ISSUE THREAD

**Issue by ReevMich** [swellstores/swell-js#53]
I added a New custom field  "sort_order" under Product.Variants and its not being return with the other variant values.

```  typescript
{
  id: "61bda8f4eee7af013d7950e9"
  name: "large"
  option_value_ids: ['61bda2b02af2a172378242f1']
  price: 25.5
  stock_level: 0
  stock_status: "out_of_stock"
}
```

**Comment by rodrigoddalmeida** [comment]
It should be possible to do this by adding custom permissions to that field in your public API key. 

Go to _Developer > Console_ and `PUT /:clients/:self/keys/<public_key_id>` with:

```json
{
  "permissions": {
    "products": {
      "fields": ["variants.sort_order"]
    }
  }
}
```

You can fetch the exact <public_key_id> you need from `GET /:clients/:self/keys`. Should be the public key you use on your storefront.
