### ISSUE TITLE
Filter a product by nested object array values

### ISSUE THREAD

**Issue by tiavina-mika** [swellstores/swell-js#56]
I have a products like this:
```
[
  {
    name: 'Product 1',
    attributes: {
      width: '15',
      minimum_required_images: '1',
      height: '20',
      channels: ['web', 'mobile']
    }
  },
    {
    name: 'Product 2',
    attributes: {
      width: '25',
      minimum_required_images: '2',
      height: '30',
      channels: ['mobile']
    },
  }
]
```

I want to filter it by a channel or list of channels,
for ex. I want to list only products with channels : ['mobile']

how should I achieve this?

**Comment by ericingram** [comment]
With Swell.js, you can filter products by attributes using the following syntax:

```
await swell.products.list({
  $filters: {
    channel: ['mobile']
  }
})
```

See more examples in the docs https://developers.swell.is/frontend-api/products#filtering

**Comment by tiavina-mika** [comment]
It worked.
Another warkaround is:
```
await swell.products.list({
  "attributes.channels": 'web',
});
```
