### ISSUE TITLE
Not getting category_index property in the products list on frontend

### ISSUE THREAD

**Issue by gauravkrp** [swellstores/swell-js#60]
I am fetching the products list by using swell front-end APIs - [https://developers.swell.is/frontend-api/products](https://community.swell.is/home/leaving?allowTrusted=1&target=https%3A%2F%2Fdevelopers.swell.is%2Ffrontend-api%2Fproducts)

In the developer console, I checked that product model contains a category_index key which contains a list of category ids. I was getting this field earlier, but since yesterday, the frontend-API has been returning my error saying that I don't have permission to expand this field.

I'm attaching console error log and my code that I've been using below.

![image](https://user-images.githubusercontent.com/12250556/188819958-404efdf7-5081-4ae5-b96c-db0fd409427f.png)

![image](https://user-images.githubusercontent.com/12250556/188820068-5649d498-8ba0-49cd-b166-7e931bfd3ee2.png)

**Comment by logeshswell** [comment]
Yes, you can expand on categories but not on `category_index` field.
@gauravkrp So, please remove `category_index` field and try it.
