### ISSUE TITLE
Shipping not working

### ISSUE THREAD

**Issue by olegkorol** [swellstores/swell-js#61]
Hi. Any update on this?
https://community.swell.is/discussion/577/shipping-services-problem

Running `PUT /settings/shipments?currency=XYZ` does the trick, but that cannot be the end solution, right?

**Comment by rodrigoddalmeida** [comment]
From the community thread:

> We found the issue causing this problem. When you first edit any shipping setting, it sets the base currency for shipping  services to your initial currency. We'll fix that soon, but a quick workaround is to update the currency on your shipping settings to match your actual base currency, like this:
> 
> `PUT /settings/shipments?currency=XYZ`

**Comment by olegkorol** [comment]
Which I already mentioned in the initial question. But this cannot be the solution, right?

**Comment by ericingram** [comment]
@olegkorol It's definitely not the solution but it's a workaround - on the backlog to fix
