### ISSUE TITLE
CJS in swell-esm.js

### ISSUE THREAD

**Issue by glesbygdn** [swellstores/swell-js#62]
Could you please transpile the esm module without `require` so we can use swell-client with Vite for example?

`try{var t=n&&n.require&&n.require("util").types`

**Comment by logeshswell** [comment]
@greph Your thoughts on this?

**Comment by glesbygdn** [comment]
To clarify, this is the result when trying to build a sveltekit project:

![image](https://user-images.githubusercontent.com/60799322/192805121-f5eb7459-954d-4062-8d4b-14d8151244b7.png)

**Comment by greph** [comment]
Hey @glesbygdn cc @logeshswell , I've added an MR to remove the (mixed) require statement and hopefully fix this issue. Will update here once merged!

**Comment by markus-gx** [comment]
updates on this? :)

**Comment by greph** [comment]
Hey @markus-gx updates have been reviewed and merged. 3.17.7  just needs to be deployed cc @swellmike

**Comment by markus-gx** [comment]
Same here as glesbygdn metnioned... @greph

**Comment by greph** [comment]
Thanks for your patience folks - 3.17.7 is now available. @markus-gx @glesbygdn

**Comment by markus-gx** [comment]
Thank you - works now ;)
