### ISSUE TITLE
Cannot add items to cart?

### ISSUE THREAD

**Issue by olegkorol** [swellstores/swell-js#63]
Could you please have a look at this?
https://community.swell.is/discussion/656/cannot-create-a-cart-anymore

**Comment by logeshswell** [comment]
@olegkorol Very sorry for the inconvenience.

I could also reproduce this issue and I see a CORS error on `setItems` method with item details present in it.

I raised a bug ticket internally for faster resolution.

**Comment by rodrigoddalmeida** [comment]
Closing this in favor of the community thread.
