### ISSUE TITLE
Please publish 3.17.7 on npm

### ISSUE THREAD

**Issue by stafyniaksacha** [swellstores/swell-js#65]
3.17.7 contains fix for isomorphic fetch, can you release it on npm ? 

Also, where is the development branch ? I only see stale branches

**Comment by rodrigoddalmeida** [comment]
@stafyniaksacha 3.17.7 should be published. Feel free to upgrade to newer versions (3.17.9 at the moment) as well, as they might play nicer with bundling systems.
