### ISSUE TITLE
Getting full list of categories from a product record.

### ISSUE THREAD

**Issue by vettloffah** [swellstores/swell-js#68]
I'm trying to create breadcrumbs in my store by getting a list of categories from a `product` record, but only the top level category is returned in the query.

Im my specific example, my product is under `Products > Parts > X-6`. When I get the product with categories expanded, I'm only returned `Products`.

Is there a way to get the full category list when doing a product query? Or is there another method I can use to create breadcrumb links from a product?

**Comment by ericingram** [comment]
We need to solve this still
