### ISSUE TITLE
Stripe error when upgrading from 3.17.10 to 3.18.2

### ISSUE THREAD

**Issue by romainbriand** [swellstores/swell-js#78]
Hello,

When upgrading from version 3.17.10 to 3.18.2, I'm getting the following error when trying to pay by card with Stripe.

`Missing value for stripe.confirmCardSetup intent secret: value should be a client_secret string.`

I believe it's due to change coming in version 3.17.11 but I have no idea how to fix this as I see no changes in the documentation.
No problem when downgrading to version 3.17.10.

Thanks for you help.

**Comment by romainbriand** [comment]
The 3.17.11 release note mentions "Fix: Added support for Stripe's SetupIntents".

**Comment by gusfune** [comment]
Hi @romainbriand - we have identified the same issue in here and have reported to Swell. They are looking into it.

**Comment by rodrigoddalmeida** [comment]
>  https://github.com/swellstores/swell-js/issues/79#issuecomment-1372617247
>  @y3owk1n, @gusfune we're looking to push a fix real soon.

@romainbriand sorry about the delayed response, I'll update here when the fix is published.

**Comment by swellmike** [comment]
The fix is now available in swell-js v3.18.3
https://www.npmjs.com/package/swell-js
