### ISSUE TITLE
Questions on the types declaration for 3.19.2

### ISSUE THREAD

**Issue by y3owk1n** [swellstores/swell-js#80]
How can we use the types declaration, it doesn't come into the dist folder upon updating to this. Do we need to somehow copy it to our project instead?

**Comment by gusfune** [comment]
I can confirm that the type declarations are not bundled with the distribution package.

![Screenshot 2023-01-11 at 20 08 22](https://user-images.githubusercontent.com/1147240/211908054-1fbe7bab-3e61-45f6-89e3-b6ebb1cba3d9.png)

**Comment by greph** [comment]
Thanks @y3owk1n , @gusfune , thanks for calling this out. We're working a fix to include the types files within the distribution.

**Comment by swellmike** [comment]
swell-js v3.19.3 has been published, which should include the types files within the dist.
