### ISSUE TITLE
Type issues in 3.19.3

### ISSUE THREAD

**Issue by gusfune** [swellstores/swell-js#81]
I've noticed a few type issues in the latest package with embedded types:

1. `swell.cart.submitOrder` is missing, even though documented at https://developers.swell.is/frontend-api/orders#submit-an-order
2. On `swell.payment.createElements` all functions are synchronous, not accepting async functions. I'd suggest changing to `() => Promise<void>` as it makes sense to do asynchronous actions in methods such as `onSuccess` or `onError`, Actually all the `InputPaymentElementCard` are syncronous.
3. Still on `swell.payment.createElements`, the method `onError` for payPal only accepts `void`, shouldn't it be a `(error) => void` so we can read the error in error?
4. On `swell.payment.createElements`, for `card`, it is not recognising `separateElements: boolean`, as specified here: https://developers.swell.is/frontend-api/payments#render-a-stripe-card-element
5. `Swell.init` forces me to explicitly declare all options if I have an option, probably because the type is:
```
interface InitOptions {
  currency: string;
  key: string;
  locale: string;
  previewContent: boolean;
  session: string;
  store: string;
  timeout: number;
  useCamelCase: boolean;
  url: string;
  vaultUrl: string;
}
```

Should actually be:
```
interface InitOptions {
  currency?: string;
  key?: string;
  locale?: string;
  previewContent?: boolean;
  session?: string;
  store?: string;
  timeout?: number;
  useCamelCase?: boolean;
  URL?: string;
  vaultUrl?: string;
}
```

6. `Swell.cart.applyCoupon` doesn't have `applyCoupon`, but it's part of the specs: https://developers.swell.is/frontend-api/coupons#apply-a-coupon
7. `Swell.cart.setItems([])` is invalid because it only accepts an array with `CartItem` inside, but this should be accepted as specified https://developers.swell.is/frontend-api/carts#empty-the-cart
8. Types are not explicitly exported. So if I try to use any typecasting for example for `Products` I can't because `Swell` only exports: `BaseModel`, `Discount`, `InitOptions`, `ResultResponse`, `SnakeToCamelCase` and `Tax`. If I want to use specific types that were already in the root export in `@types/swell-js`, I need to change my import to `import type { Product } from "swell-js/types/product"` instead of just using `import type { Product } from "swell-js"`

**Comment by markus-gx** [comment]
The Query types we had in @types/swell-js is missing too. 
Probably they are not completely correct or fully complete, but better than an `object` type :) 

`export interface ProductQuery extends Query {
    category?: string;
    categories?: string[];
    $filters?: unknown;
}

export interface Query {
    limit?: number;
    page?: number;
    expand?: string[];
}

export interface SearchQuery extends Query {
    search: string;
}`

**Comment by greph** [comment]
Thanks @gusfune and @markus-gx for the feedback! We'll work to incorporate these updates into an upcoming release.

**Comment by gusfune** [comment]
Hi @greph I see you have updated to 3.19.4 and a lot of the changes are in place. This seems to be mostly retro-compatible now.

The only type I saw issues was `ContentObject`, which are only considering single-fields content objects. This means if we have content with contain objects or arrays, it won't work because of how it's defined as:
```
interface ContentObject {
  [key: string]: string | number | boolean | null;
}
```

One possible solution would be making it a `Record` that also accepts `Records`, or even making it recursive so a `ContentObject` can take a `ContentObject` inside, but still, would need to consider the `Array` scenarios.

Or the easy way would just make it `unknown` or `any`. Being the first option for each customer case override with their own typings, or `any` to simply turn off type-safety on customer-defined content models.

**Comment by gusfune** [comment]
Also, the CreateElement seems to be with issues still. Just noticed the current types are:
```
export interface InputPaymentElementCard {
  elementId?: string; // default: #card-element
  options?: object;
  onChange?: void; // optional, called when the Element value changes
  onReady?: void; // optional, called when the Element is fully rendered
  onFocus?: void; // optional, called when the Element gains focus
  onBlur?: void; // optional, called when the Element loses focus
  onEscape?: void;
  onClick?: void; // optional, called when the Element is clicked
  onSuccess?: void; // optional, called on card payment success
  onError?: void; // optional, called on card payment error
}
```

But should actually be something like: `onError?: (error: unknown) => void` or `onError?: () => void`. It currently doesn't accept the function to be attached to it in a type-safe manner.

Also, if we use `Product` as input and we have cases where `variants` come within `results`, that won't check because it doesn't consider for extended queries to come, not exports Query results to be type-casted.

**Comment by greph** [comment]
Thanks @gusfune for the content type suggestion. As for the payment types, those are being worked on as part of a separate MR and should be released shortly.

**Comment by gusfune** [comment]
Hi @mustafahoda and @greph thanks for the followup. After trying out 3.19.10 I still find a few inconsistencies/errors, lt's go over it:

### 1. Payment Elements
The `elementId` is missing from `InputPaymentElementCard` type. Here is an [example below from the documentation](https://developers.swell.is/frontend-api/payments#render-a-stripe-card-element):
```
swell.payment.createElements({
  card: {
    elementId: '#card-element-id', // default: #card-element
    options: {
      // options are passed as a direct argument to stripe.js
      style: {
        base: {
          fontWeight: 500,
          fontSize: '16px'
        }
      }
    }
```

Error is:
> Object literal may only specify known properties, and 'elementId' does not exist in type 'InputPaymentElementCard'.ts(2322)

### 2. Purchase Options
If I call `purchaseOptions` from a product, it says I can't call `purchaseOptions?.standard` directly because Purchase Options is set as an Array, while at least as far I can see, it's a dictionary with standard and subscriptions as possible keys.

### 3. Image
The type `ImageSnake` is missing `id`.

### 4. Cart Input
The function SetItems for Cart is defined as:
```
function setItems(input: [CartItem?]): Promise<Cart>;
```

That means it only accepts one single CartItem in an array as an input, not a variety of CartItems. This should be:
```
function setItems(input?: CartItem[]): Promise<Cart>;
```

Or `Array<CartItem>` if that syntax rocks your boat.
This extends to the `Cart` definition itself that defines Items as `items?: [CartItemSnake];`

### 5. Snake Types inside Camel Types
For example, inside `Product` you find `PriceSnake[]` in `prices`, not `Prices[]`.
Or `attributeId` inside `ProductOptions`.


### 6. Other minor types
Some small stuff missing such as:
- Coupons
- Discounts
- Categories (inside products)
- `CaptureTotal` missing from `Cart`

**Comment by gusfune** [comment]
Just a correction on item 4, when defining a type `[LikeThis]`, it's not exactly an array, but a tuple.

**Comment by gusfune** [comment]
One more update, it seems `bundle_items` inside `CartItem` is a tuple, not an array.
