### ISSUE TITLE
Can't update shipping.price (permission error)

### ISSUE THREAD

**Issue by rome2o** [swellstores/swell-js#83]
Hi there,

We are trying to update the shipping price for our checkout. We are using the following code.

```
      await swell.cart.update({

        shipping: {
          service: deliveryArray.join(),
          price: 1000,
          deliveries,
          instructions,
        },
      });
```

However it seems that with storefront token we are not able to update the price of the shipping? 

```
{
    "code": "permission_error",
    "message": "You are not allowed to update `price`",
    "param": "price"
}
```

Please let us know what is to be done to fix this.

Thanks

**Comment by ericingram** [comment]
That's right, generally you don't want to enable end-users to change pricing which could happen if you enabled that permission. Instead, you should have a server-side function handle that request, and ensure it follows your specific rule set.

**Comment by rome2o** [comment]
@ericingram - thanks for clarifying! :) 

Is there any recommended or standard way of doing this or should it just be a plain request to the server as user starts going to the payment page?

**Comment by ericingram** [comment]
A request to do this on the server-side (swell-node) would look similar to the frontend (swell-js):

```
      await swell.put('/carts/{id}', {
        id: cartId,
        shipping: {
          service: deliveryArray.join(),
          price: 1000,
          deliveries,
          instructions,
        },
      });
```

**Comment by rome2o** [comment]
Thanks @ericingram. 

For those who might come across this thread, we ended up creating an endpoint which will receive the `cart_id` in order to assign the shipping price on the basis of `shipping.service` and picking up rates from `shipment_ratings`. 

The issue is resolved.

**Comment by dalley8626** [comment]
It would be really nice if swell-js goes full cms, as it does provide alot of flexibility

**Comment by ericingram** [comment]
We do plan to introduce new CMS functionality this year, while also improving support for dedicated CMS platforms.

**Comment by dalley8626** [comment]
That would be perfect @ericingram. As right now i am struggle finding a way to actually update the cart's shipment, i am trying to create a quick nextjs endpoint, however this doesn't seem to be working

```
import type { NextApiRequest, NextApiResponse } from "next";
import { swellAPI } from "../../../lib/swell-api";

export default async function cartHandler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const { id } = req.body;

  try {
    await swellAPI.put(`/carts/${id}`, {
      id: id,
      shipment_price: 10,
      shipment_method: "express",
      shipping: {
        price: 10,
        method: "express",
      },
    });

    const cart = await swellAPI.get(`/carts/${id}`);
    console.log("cart", cart);
  } catch (e) {
    res.status(500).json({ message: "Error updating product" });
  }

  res.status(200).json({ message: "Product updated successfully" });
}


```

**Comment by rome2o** [comment]
@dalley8626 - this might be of help for you

```
const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  try {
    if (req.method !== 'POST') {
      throw new Error('Only POST requests are accepted');
    }

    if (!process.env.NEXT_SWELL_PRIVATE_KEY) {
      throw new Error('Something has gone wrong secret token');
    }
    const { cartId } = req.body;
    if (!cartId) throw new Error('cart_id is a required field.');

    const swell = swellNode.init(
      process.env.NEXT_SWELL_PUBLIC_STORE as string,
      process.env.NEXT_SWELL_PRIVATE_KEY
    );
  
    const cart = await swell.put(`/carts/${cartId}`, {
      shipping: {
        price: 100,
        service: 'test',
        service_name: 'test',
        // !NOTE: Yes we can add additional keys here if we ought to.
      },
    });

    res.status(200).json({
      message: 'Shipping price updated successfully',
      status: true,
      payload: { ...cart },
    });
  } catch (error: any) {
    res.status(500).json({
      message: error?.message ?? 'Something went wrong',
      status: false,
    });
  }
};
```

**Comment by dalley8626** [comment]
@rome2o i tried that, it doesn't seem to be updating the database for me, while it does send me the correct response

**Comment by rome2o** [comment]
@dalley8626  Are you using right ID to fetch the cart (keep in mind that id is different than what you might be thinking to use)? Because the response that you showed above seems to be for a new cart as your cart checkout id is different on frontend. Also notice that the frontend sessions are not available on the backend.

**Comment by dalley8626** [comment]
It's working now, thank u very much guys @rome2o there's something wrong with my input id
