### ISSUE TITLE
CORS error on removeItem from cart

### ISSUE THREAD

**Issue by soyzamudio** [swellstores/swell-js#87]
I started a new project with Swell, I am able to fetch products and categories, fetch carts, add items to cart, but whenever I try to remove an Item from the cart I get the following error:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3433118/216115552-469b9452-7ffd-4d01-98f9-b83eb924468c.png">

any help would be greatly appreciated.

I am using swell-js@^3.19.4 and angular

**Comment by rodrigoddalmeida** [comment]
Hi @soyzamudio, could you share a code snippet of your `removeItem` call? That error generally means that you are trying to remove a non-existing item from a cart. Cart items have their own IDs, which are different than the product ID used to add them to the cart.

**Comment by soyzamudio** [comment]
Ohhh that makes more sense, when I pass the `CartItem` id instead of the `Product` id it works like a charm! Thanks @rodrigoddalmeida
