### ISSUE TITLE
Interface AddressSnake is missing account_address_id

### ISSUE THREAD

**Issue by osseonews** [swellstores/swell-js#92]
In your types in SwellJs you have Interface AddressSnake, and this is called for the shipping object in AccountSnake. However, shipping object on the account is allowed to have a field called account_address_id, but if you attempt to do that, you get an TS error. You should add: account_address_id?:string to the AddressSnake. Thanks.

**Comment by greph** [comment]
Thanks @osseonews for the heads-up. We've merged the change, which should be reflected in the next release.

**Comment by greph** [comment]
The update has been released with v3.19.10
