### ISSUE TITLE
Type definitions missing error object in return type

### ISSUE THREAD

**Issue by vettloffah** [swellstores/swell-js#96]
When an api call doesn't succeed, there is an "errors" property returned from swellj-s. For example:

```js
const cart = await swell.cart.get()
if(cart.errors){
 // handle errors
}
```

This isn't accounted for the in the type definitions. The return type is just `Promise<swell.Cart>` and Cart doesn't include `errors` so trying to handle errors is showing a type error warning as of swell-js 3.21.2

**Comment by lukifer** [comment]
This is still an issue, as of 4.1.1. We're currently having to work around it:
```
export type SwellCardErrors = {
  errors: {
    gateway: {
      message: string;
    };
  };
};

const card = await swell.account.createCard(updatedCard);
if ('errors' in (card as any)) {
  const { errors } = card as any as SwellCardErrors;
  if (typeof errors === 'object' && 'gateway' in errors)
    throw new Error(errors.gateway.message);
...
}
```

**Comment by steven-k1** [comment]
A fix was deployed for this

**Comment by steven-k1** [comment]
A fix was deployed for this

**Comment by lukifer** [comment]
@awwit @steven-k1 Been working from our end, no issues so far, will reach out if we encounter further issues. Thanks for taking care of it!

**Comment by steven-k1** [comment]
@lukifer Glad to hear. Thanks for confirming.
