### ISSUE TITLE
Stock status type missing some string values

### ISSUE THREAD

**Issue by RyanWarner** [swellstores/swell-js#97]
I'm working on an "Add to cart" button. I want to conditionally change that to be a non-interactive element when my product is out of stock.

While doing this I ran into what I believe is a type issue with stock status: it's missing `in_stock` and `out_of_stock`

https://github.com/swellstores/swell-js/blob/master/types/product/snake.d.ts#L164

```
stock_status?: 'available' | 'preorder' | 'backorder';
```

Here is a snippet the object as returned by Swell JS:

<img width="331" alt="Screen Shot 2023-03-28 at 8 59 22 AM" src="https://user-images.githubusercontent.com/1595979/228244485-772bd278-2a35-4483-a237-38b6e701dd14.png">

**Comment by awwit** [comment]
@RyanWarner a fix for this issue is available in version `3.21.4`.
